# Generated by Django 2.2.9 on 2020-01-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='average_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='max_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='median_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='min_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='mode_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='number',
            field=models.PositiveSmallIntegerField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='skipped_classes',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='specialty_name',
            field=models.CharField(default='electrition', max_length=255),
        ),
        migrations.AlterField(
            model_name='group',
            name='specialty_number',
            field=models.PositiveSmallIntegerField(default=141),
        ),
        migrations.AlterField(
            model_name='group',
            name='standard_deviation_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
