# Generated by Django 2.2.9 on 2020-01-21 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='group',
            name='max_rating',
        ),
        migrations.RemoveField(
            model_name='group',
            name='median_rating',
        ),
        migrations.RemoveField(
            model_name='group',
            name='min_rating',
        ),
        migrations.RemoveField(
            model_name='group',
            name='mode_rating',
        ),
        migrations.RemoveField(
            model_name='group',
            name='skipped_classes',
        ),
        migrations.RemoveField(
            model_name='group',
            name='standard_deviation_rating',
        ),
        migrations.AddField(
            model_name='group',
            name='head_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='head_student', to='students.Student'),
        ),
        migrations.AddField(
            model_name='group',
            name='head_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='head_teacher', to='teachers.Teacher'),
        ),
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.Group'),
        ),
    ]
