# Generated by Django 2.2.9 on 2020-01-15 06:08

from django.db import migrations, models
import students.fields


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20200109_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('message', students.fields.JSONField()),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
    ]
