# Generated by Django 2.2.9 on 2020-01-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20200106_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='number',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
