# Generated by Django 2.2.9 on 2020-01-16 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_file',
            field=models.FileField(blank=True, null=True, upload_to='messages/'),
        ),
    ]
