# Generated by Django 2.2.9 on 2020-02-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_logger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logger',
            name='user_id',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
